News/urls.py
from django.urls import path
from . import views

app_name = "News"
urlpatterns = [
    path("api/news/", views.NewsListAPIView.as_view(), name="news_list"),
    path("api/news/<int:pk>",
         views.NewsDetailAPIView.as_view(), name="news_detail"),
    path("api/news/tags/<int:pk>",
         views.TagDetailAPIView.as_view(), name="tag_detail"),
    path("api/news/tags", views.TagListAPIView.as_view(), name="tag_list")
]

Sandans/urls.py
from django.urls import path
from Sandans.views import SandanListAPIView, SandanWaittimeOrderAPIView, WaittimeUpdate, Login

app_name = "Sandans"
urlpatterns = [
    path("api/sandans", SandanListAPIView.as_view(), name="sandan_list"),
    path("api/sandans/waittime_order",
         SandanWaittimeOrderAPIView.as_view(), name="sandan_waittime_order"),
    path("sandans/waittime_update",
         WaittimeUpdate.as_view(), name="waittime_update"),
    path("login", Login.as_view(), name="login"),
]

kaiseifes_150th_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("News.urls")),
    path("", include("AdminControl.urls")),
    path("", include("Subscribers.urls")),
    path("", include("Sandans.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sandans/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid
# Create your models here.


class Sandan(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    icon = models.ImageField(null=False, blank=False, upload_to="icons/")
    waittime = models.IntegerField(default=0)
    last_updated = models.DateTimeField(auto_now=True)


class OnlineSandan(models.Model):
    icon = models.ImageField(null=True, upload_to="icons/")
    links = models.URLField(blank=True, null=True)
    books = models.FileField(
        upload_to="books/", blank=True, null=True)
    description = models.TextField()

Sandans/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from .models import Sandan


class WaittimeUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["placeholder"] = field.label

    class Meta:
        model = Sandan
        fields = ('waittime',)


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["placeholder"] = field.label

    class Meta:
        model = Sandan

Sandans/views.py
from datetime import datetime, timezone, timedelta

from django.shortcuts import render, redirect
from django.views.generic import UpdateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse

from django.contrib.auth.views import LoginView

from rest_framework.generics import ListAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK

from Sandans.models import Sandan
from Sandans.serializers import SandanSerializer
from .forms import WaittimeUpdateForm, LoginForm

JST = timezone(timedelta(hours=+9), 'JST')

# Create your views here.


class SandanListAPIView(ListAPIView):
    permission_classes = (AllowAny,)
    queryset = Sandan.objects.all()
    serializer_class = SandanSerializer

    def get(self, request):
        sandan_list = [[sandan.id, sandan.username, sandan.waittime]
                       for sandan in Sandan.objects.filter(is_superuser=False)]
        ret = [{"id": sandan[0], "name":sandan[1], "waittime":sandan[2]}
               for sandan in sandan_list]
        return Response(data=ret, status=HTTP_200_OK)


class SandanWaittimeOrderAPIView(ListAPIView):
    permission_classes = (AllowAny,)
    queryset = Sandan.objects.all()

    def get(self, request):
        sandan_list = [[sandan.id, sandan.username, sandan.waittime]
                       for sandan in Sandan.objects.filter(is_superuser=False)]
        ret = [{"id": sandan[0], "name":sandan[1], "waittime":sandan[2]}
               for sandan in sorted(sandan_list, key=lambda x: x[2])]
        return Response(data=ret, status=HTTP_200_OK)


class WaittimeUpdate(LoginRequiredMixin, UpdateView):
    template_name = "Sandans/waittime_update.html"
    login_url = "/login"
    form_class = WaittimeUpdateForm
    success_url = reverse_lazy("Sandans:waittime_update")

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "待ち時間を変更しました")
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        return get_object_or_404(Sandan, id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['alert'] = True if datetime.now(
            JST)-self.request.user.last_updated > timedelta(minutes=10) else False
        return context


class Login(LoginView):
    form_class = LoginForm
    template_name = "Sandans/login.html"

    def form_valid(self, form):
        messages.success(self.request, "ログインしました。")
        return super().form_valid(form)

Sandans/templates/Sandans/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}ログインする{% endblock %}
{% block content %}
<div class="form-card col-xs-6 col-md-4 p-5 mx-auto mt-5">
    <h2 class="form-title mb-4 d-flex justify-content-center">ログイン</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label class="form-label">参団番号</label>
            {% render_field form.username class="form-control" placeholder="参団番号" %}
            {% for error in form.name.errors %}
            <div class="alert alert-danger mt-2" role="alert">
                <p>{{ error }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="form-group mb-5">
            <label class="form-label">パスワード</label>
            {% render_field form.password class="form-control" placeholder="パスワード" %}
            {% for error in form.name.errors %}
            <div class="alert alert-danger mt-2" role="alert">
                <p>{{ error }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="text-end">
            <button class="btn btn-outline-dark" type="submit">ログイン</button>
        </div>
    </form>
</div>
{% endblock %}

Sandans/templates/Sandans/waittime_update.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}
{% block title %}待ち時間を更新{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'Sandans/waittime_update.css' %}">
<main>
    <div class="form-card col-xs-6 col-md-4 p-3 mx-auto mt-md-3">
        <div class="d-flex justify-content-between flex-column flex-lg-row mb-3">
            <p>&lt; <a href="{% url 'Sandans:login' %}">別の参団でログインする</a></p>
            {% if not alert %}
            <p style="color: rgba(0, 0, 0, 0.5);">最終更新：{{request.user.last_updated|naturaltime}}</p>
            {% else %}
            <p class="text-danger">⚠︎ 最終更新：{{request.user.last_updated|naturaltime}}</p>
            {% endif %}
        </div>
        <h2>{{request.user.first_name}}</h2>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label">現在の待ち時間</label>
                {% render_field form.waittime class="form-control" placeholder="更新" %}
                <p style="display: block;text-align: right;font-size: 3rem;">分</p>
                {% for error in form.name.errors %}
                <div class="alert alert-danger mt-2" role="alert">
                    <p>{{ error }}</p>
                </div>
                {% endfor %}
            </div>
            <div style="text-align: right;">
                <button class="btn btn-outline-dark" type="submit">更新</button>
            </div>
        </form>
    </div>
</main>
{% endblock %}